[phases.setup]
nixPkgs = ["php82", "php82Extensions.gd", "php82Extensions.pdo_pgsql"]

[phases.build]
cmds = ["composer install --no-interaction --prefer-dist --optimize-autoloader"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
