[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.gd",
  "php82Extensions.pdo_pgsql",
  "php82Extensions.zip"
]

[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"
